export { defaultVariant, useActiveVariant } from './model/useActiveVariant'
export type { ActiveVariantKind, ActiveVariantView } from './model/useActiveVariant'
export { explanationFor } from './model/explanations'
export { useAutoRecommendation } from './model/useAutoRecommendation'
export { useManualRecommendation } from './model/useManualRecommendation'
export { SearchStats } from './ui/searchStats'
export { StressSwitch } from './ui/stressSwitch'
