from typing import Any, Protocol, TypeVar


ModelT = TypeVar("ModelT")


class RepositoryInterface(Protocol[ModelT]):
    async def get_item(self, item_id: Any) -> ModelT | None: ...
    async def get_by_filter(self, **filters: Any) -> ModelT | None: ...
    async def add(self, **data: Any) -> ModelT: ...
    async def update_item(self, item_id: Any, **data: Any) -> ModelT | None: ...
    async def delete_item(self, item: ModelT) -> None: ...
